netflix/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ShowController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\TvController;
use App\Http\Controllers\ActeurController;
use App\Http\Controllers\GenreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ShowController::class, 'index']);

Route::resource('home', ShowController::class);

Route::resource('movies', MovieController::class);

Route::resource('tv', TvController::class);

Route::resource('acteur', ActeurController::class);

Route::resource('genre', GenreController::class);

require __DIR__.'/auth.php';

netflix/resources/views/acteurs.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../../resources/css/style.css">
@endsection

@section('contenu')
<h2> {{ $shows[0]->cast }}</h2>
    <div class="gridContainer">
        <div class="grid">
            @foreach($shows as $show)
            <a class="imgLink" href="{{ route('home.show', $show->id) }}"> <img class="grow" src=" {{ $show->img }} "/> </a>
            @endforeach
        </div>
    </div>
@endsection

netflix/resources/views/genres.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../../resources/css/style.css">
@endsection

@section('contenu')
<h2> {{ $shows[0]->genre }}</h2>
    <div class="gridContainer">
        <div class="grid">
            @foreach($shows as $show)
            <a class="imgLink" href="{{ route('home.show', $show->id) }}"> <img class="grow" src=" {{ $show->img }} "/> </a>
            @endforeach
        </div>
    </div>
@endsection

netflix/resources/views/index.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../resources/css/style.css">
@endsection

@section('contenu')
    <!-- Caroussel anime-->
    <div class="category">
        <h2 class="cat_title">
            Animes :
        </h2>

        <!-- Caroussel -->
        <div class="carousel">
        @foreach($animes->shuffle() as $anime)
            <div class="show">
                <a class="imgLink" href="{{ route('home.show', $anime->id) }}"> <img class="grow" src=" {{ $anime->img }} "/> </a>
            </div>    
        @endforeach
        </div>
    </div>

    <!-- Caroussel sci-fi-->
    <div class="category">
        <h2 class="cat_title">
            Films romantiques :
        </h2>

        <!-- Caroussel -->
        <div class="carousel">
        @foreach($romantics->shuffle() as $romantic)
            <div class="show">
                <a class="imgLink" href="{{ route('home.show', $romantic->id) }}"> <img class="grow" src=" {{ $romantic->img }} "/> </a>
            </div>    
        @endforeach
        </div>
    </div>

    <!-- Caroussel horror-->
    <div class="category">
        <h2 class="cat_title">
            Horreur et thrillers :
        </h2>

        <!-- Caroussel -->
        <div class="carousel">
        @foreach($horrors->shuffle() as $horror)
            <div class="show">
                <a class="imgLink" href="{{ route('home.show', $horror->id) }}"> <img class="grow" src=" {{ $horror->img }} "/> </a>
            </div>    
        @endforeach
        </div>
    </div>
@endsection

netflix/resources/views/movies.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../resources/css/style.css">
@endsection

@section('contenu')
<h2> Voici tous nos films actuellement disponibles :</h2>
<div class="gridContainer">
    <div class="grid">
        @foreach($movies as $movie)
        <a class="imgLink" href="{{ route('home.show', $movie->id) }}"> <img class="grow" src=" {{ $movie->img }} "/> </a>
        @endforeach
    </div>
</div>
@endsection

netflix/resources/views/show.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../../resources/css/style.css">
@endsection

@section('contenu')
<div class="showContainer">
    @auth
    <img class="showTitle" src=" {{ $show->img }} "/>
    <div class="showInfos">
        <h3>{{ $show->title }}</h3>
        <div class="showHoriz">
            <div class="showL">
                <div class="showLT">
                    <p class="showRecommend"> Recommandé à 78%</p>
                    <p class="showYear"> {{ $show->release_year }}</p>
                    <p class="showDuration"> {{ $show->duration }} </p>
                </div>
                <div class="showLB">
                    <p class="showDescription"> {{ $show->description }} </p>
                </div>
            </div>
            <div class="showR">
                <div class="showCat">
                    <p class="showInfoTitle">Distribution : </p>
                    <p class="showNames">{{ $show->director}}</p>
                </div>
                <div class="showCat">
                    <p class="showInfoTitle">Acteurs : </p>
                    <p class="showNames">
                        @foreach($acteurs as $acteur)
                            <a href="{{ route('acteur.show', $acteur->id) }}" class="showLink">{{ $acteur->cast }},</a>
                        @endforeach
                    </p>
                </div>
                <div class="showCat">
                    <p class="showInfoTitle">Genres : </p>
                    <p class="showNames">
                        @foreach($genres as $genre)
                            <a href="{{ route('genre.show', $genre->id) }}" class="showLink">{{ $genre->genre }},</a>
                        @endforeach
                    </p>
                </div>
            </div>
        </div>
    @else
    <h2> Vous devez être connecté pour accéder au contenu des programmes. </h2>
    @endauth
    </div>
</div>
@endsection

netflix/resources/views/tv.blade.php
@extends('layouts.homeLayout')

@section('css')
<link rel="stylesheet" href="../resources/css/style.css">
@endsection

@section('contenu')
<h2> Voici toutes nos séries actuellement disponibles :</h2>
<div class="gridContainer">
    <div class="grid">
        @foreach($tvs as $tv)
        <a class="imgLink" href="{{ route('home.show', $tv->id) }}"> <img class="grow" src=" {{ $tv->img }} "/> </a>
        @endforeach
    </div>
</div>
@endsection